### Create/Update Profile (Valid Data)
POST http://127.0.0.1:8000/api/profile/
Content-Type: application/json
Authorization: Token c31bf6b9c68f791ee41978ff1730c390d7e4c7c7

{
    "student_id": "S12345678",
    "full_name": "Test User",
    "email": "testuser_updated@test.com"
}

### Create/Update Profile (Invalid student_id Format)
POST http://127.0.0.1:8000/api/profile/
Content-Type: application/json
Authorization: Token c31bf6b9c68f791ee41978ff1730c390d7e4c7c7

{
    "student_id": "123",
    "full_name": "Test User",
    "email": "testuser_updated@test.com"
}

### Add Class with Valid Data
POST http://127.0.0.1:8000/api/add_class/
Content-Type: application/json
Authorization: Token c31bf6b9c68f791ee41978ff1730c390d7e4c7c7

{
    "course_number": "CS101",
    "section_number": "01",
    "class_name": "Introduction to Computer Science",
    "instructor": "Prof. John Doe",
    "start_time": "2025-02-10T09:00:00Z",
    "days": ["Monday", "Wednesday", "Friday"]
}

### Add different Class for Same User
POST http://127.0.0.1:8000/api/add_class/
Content-Type: application/json
Authorization: Token c31bf6b9c68f791ee41978ff1730c390d7e4c7c7

{
    "course_number": "CS201",
    "section_number": "02",
    "class_name": "Intermediate Computer Science",
    "instructor": "Prof. John Doe",
    "start_time": "2025-02-10T09:00:00Z",
    "days": ["Monday", "Wednesday", "Friday"]
}

### Add Duplicate Class for Same User
POST http://127.0.0.1:8000/api/add_class/
Content-Type: application/json
Authorization: Token c31bf6b9c68f791ee41978ff1730c390d7e4c7c7

{
    "course_number": "CS101",
    "section_number": "01",
    "class_name": "Introduction to Computer Science",
    "instructor": "Prof. John Doe",
    "start_time": "2025-02-10T09:00:00Z",
    "days": ["Monday", "Wednesday", "Friday"]
}

### Get Classes for Authenticated User
GET http://127.0.0.1:8000/api/get_classes/
Content-Type: application/json
Authorization: Token c31bf6b9c68f791ee41978ff1730c390d7e4c7c7

{

}