### Register User
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword",
    "email": "test@test.com"
}

###

### Login User
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}

###

### Invalid Login (Wrong Credentials)
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "wronguser",
    "password": "wrongpassword"
}

###

### Test Token
GET http://127.0.0.1:8000/api/test_token/
Content-Type: application/json
Authorization: Token bd53194b604990d8c84adb3b552a99feb0163af3

{

}

### Create/Update Profile (Authenticated)
POST http://127.0.0.1:8000/api/profile/
Content-Type: application/json
Authorization: Token bd53194b604990d8c84adb3b552a99feb0163af3

{
    "student_id": "S12345678",
    "full_name": "Test User",
    "email": "testuser_updated@test.com"
}



### Add Class (Authenticated)
POST http://127.0.0.1:8000/api/add_class/
Content-Type: application/json
Authorization: Token bd53194b604990d8c84adb3b552a99feb0163af3

{
    "course_number": "CS101",
    "section_number": "01",
    "class_name": "Introduction to Computer Science",
    "instructor": "Prof. John Doe",
    "start_time": "2025-02-10T09:00:00Z",
    "days": ["Monday", "Wednesday", "Friday"],
}

### Get Classes (Authenticated)
GET http://127.0.0.1:8000/api/get_classes/
Content-Type: application/json
Authorization: Token bd53194b604990d8c84adb3b552a99feb0163af3

{

}
