# Generated by Django 5.1.5 on 2025-01-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
