# Generated by Django 5.1.5 on 2025-01-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_studentprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
