# Generated by Django 5.1.5 on 2025-01-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_studentprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
