# Generated by Django 5.1.5 on 2025-01-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_studentprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatExchangeRequest',
        ),
    ]
