# Generated by Django 5.1.5 on 2025-01-24 23:24

import django.contrib.postgres.fields # type: ignore
from django.conf import settings # type: ignore
from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_delete_seatexchangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name='studentclass',
            unique_together={('user', 'course_number', 'section_number')},
        ),
    ]
