# Generated by Django 5.1.5 on 2025-01-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_studentclass_days_alter_studentclass_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='days',
            field=models.JSONField(default=list),
        ),
    ]
