# Generated by Django 5.1.5 on 2025-01-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_studentclass_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentclass',
            unique_together=set(),
        ),
    ]
