# Generated by Django 5.1.5 on 2025-01-25 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_request_requestinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestInteraction',
        ),
    ]
