# Generated by Django 5.1.5 on 2025-01-28 03:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_classtraderequest_acceptedrequest_delete_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtraderequest',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='classtraderequest',
            name='requested_class',
        ),
        migrations.RemoveField(
            model_name='classtraderequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='classtraderequest',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='classtraderequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='classtraderequest',
            name='desired_class_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='classtraderequest',
            name='desired_section_number',
            field=models.CharField(default='-1', max_length=10),
        ),
        migrations.AddField(
            model_name='classtraderequest',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtraderequest',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtraderequest',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classtraderequest',
            name='offered_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_requests', to='server.studentclass'),
        ),
        migrations.AlterField(
            model_name='classtraderequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='start_time',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AcceptedRequest',
        ),
    ]
